- (New) Responsive Web Design/Module final projects code/Building a survey form/index.html
- (New) Responsive Web Design/Module final projects code/Building a survey form/styles.css
added the final finished code and made some changes
> final added the project code

- (New) Responsive Web Design/Module final projects code/Building a technical documentation/index.html
- (New) Responsive Web Design/Module final projects code/Product landing page /index.html
- (New) Responsive Web Design/Module final projects code/Product landing page /styles.css
finalising the code in product landing page
> Second devbranch

- (New) Responsive Web Design/Module final projects code/Product landing page /index.html
this is optional message: some small changes to the code formatting to make it more readable and more accessible for future contributors
> made some small changes to the code formatting

- JavaScript Algorithms and Data Structures/06Basic Algorithmic Scripting/step016.js
- JavaScript Algorithms and Data Structures/07Object Oriented programming/step001.js
- JavaScript Algorithms and Data Structures/07Object Oriented programming/step002.js
- JavaScript Algorithms and Data Structures/07Object Oriented programming/step003.js
- JavaScript Algorithms and Data Structures/07Object Oriented programming/step004.js
- JavaScript Algorithms and Data Structures/07Object Oriented programming/step005.js
- JavaScript Algorithms and Data Structures/07Object Oriented programming/step006.js
- JavaScript Algorithms and Data Structures/07Object Oriented programming/step007.js
- JavaScript Algorithms and Data Structures/07Object Oriented programming/step008.js
- JavaScript Algorithms and Data Structures/07Object Oriented programming/step009.js
- JavaScript Algorithms and Data Structures/07Object Oriented programming/step010.js
- JavaScript Algorithms and Data Structures/07Object Oriented programming/step011.js
finishing up the challenges in freecodecamp
> added files from OOP freecodecamp

- JavaScript Algorithms and Data Structures/07Object Oriented programming/step011.js
finishing up some of the javascript files
> adding some more completed files

- JavaScript Algorithms and Data Structures/05Basic Data Structures/step001.js
- JavaScript Algorithms and Data Structures/05Basic Data Structures/step002.js
- JavaScript Algorithms and Data Structures/05Basic Data Structures/step003.js
- JavaScript Algorithms and Data Structures/05Basic Data Structures/step004.js
- JavaScript Algorithms and Data Structures/05Basic Data Structures/step006.js
- JavaScript Algorithms and Data Structures/05Basic Data Structures/step007.js
- JavaScript Algorithms and Data Structures/05Basic Data Structures/step008.js
- JavaScript Algorithms and Data Structures/05Basic Data Structures/step009.js
- JavaScript Algorithms and Data Structures/05Basic Data Structures/step010.js
- JavaScript Algorithms and Data Structures/05Basic Data Structures/step011.js
- JavaScript Algorithms and Data Structures/05Basic Data Structures/step012.js
- JavaScript Algorithms and Data Structures/05Basic Data Structures/step013.js
- JavaScript Algorithms and Data Structures/05Basic Data Structures/step014.js
- JavaScript Algorithms and Data Structures/05Basic Data Structures/step015.js
- JavaScript Algorithms and Data Structures/05Basic Data Structures/step016.js
- JavaScript Algorithms and Data Structures/05Basic Data Structures/step017.js
- JavaScript Algorithms and Data Structures/05Basic Data Structures/step018.js
- JavaScript Algorithms and Data Structures/05Basic Data Structures/step019.js
- JavaScript Algorithms and Data Structures/07Object Oriented programming/step012.js
- JavaScript Algorithms and Data Structures/07Object Oriented programming/step013.js
- JavaScript Algorithms and Data Structures/07Object Oriented programming/step014.js
- JavaScript Algorithms and Data Structures/07Object Oriented programming/step015.js
made changes to the file containing the main algorithm questions
> added more challenges files

- JavaScript Algorithms and Data Structures/05Basic Data Structures/step020.js
- JavaScript Algorithms and Data Structures/06Basic Algorithmic Scripting/step001.js
- JavaScript Algorithms and Data Structures/06Basic Algorithmic Scripting/step002.js
- JavaScript Algorithms and Data Structures/06Basic Algorithmic Scripting/step003.js
- JavaScript Algorithms and Data Structures/06Basic Algorithmic Scripting/step004.js
- JavaScript Algorithms and Data Structures/06Basic Algorithmic Scripting/step005.js
- JavaScript Algorithms and Data Structures/06Basic Algorithmic Scripting/step006.js
completed freecodecamp challenges
> ADD: completed challenges

- Data Visualisation Certification/01Data Visualisation with D3/step029.html
- JavaScript Algorithms and Data Structures/01Basic Javascript/step006.js
- JavaScript Algorithms and Data Structures/01Basic Javascript/step007.js
- JavaScript Algorithms and Data Structures/01Basic Javascript/step008.js
- JavaScript Algorithms and Data Structures/01Basic Javascript/step009.js
- JavaScript Algorithms and Data Structures/01Basic Javascript/step010.js
- JavaScript Algorithms and Data Structures/01Basic Javascript/step025.js
- JavaScript Algorithms and Data Structures/01Basic Javascript/step027.js
made some small changes for improving the look of the code and also some minor formatting changes I learnt from youtube
> ADD some small changes to older push

- 06Back End Development and API's/02Basic Node and Express/012Get Data from POST Requests.js
- 06Back End Development and API's/03MongoDB and Mongoose/001Install and Set Up Mongoose/.env
- 06Back End Development and API's/03MongoDB and Mongoose/001Install and Set Up Mongoose/myApp.js
- 06Back End Development and API's/03MongoDB and Mongoose/001Install and Set Up Mongoose/package.json
- 07Quality Assurance/01Quality Assurance and Testing with Chai/01Learn How JavaScript Assertions Work.js
- 07Quality Assurance/01Quality Assurance and Testing with Chai/02Test if a Variable or Function is Defined.js
- 07Quality Assurance/01Quality Assurance and Testing with Chai/03Use Assert.isOK and Assert.isNotOK.js
- 07Quality Assurance/01Quality Assurance and Testing with Chai/04Test for Truthiness.js
- 07Quality Assurance/01Quality Assurance and Testing with Chai/05Use the Double Equals to Assert Equality.js
- 07Quality Assurance/01Quality Assurance and Testing with Chai/06Use the Triple Equals to Assert Strict Equality.js
- 07Quality Assurance/01Quality Assurance and Testing with Chai/07Assert Deep Equality with .deepEqual and .notDeepEqual.js
- 07Quality Assurance/01Quality Assurance and Testing with Chai/08Compare the Properties of Two Elements.js
- 07Quality Assurance/01Quality Assurance and Testing with Chai/09Test if One Value is Below or At Least as Large as Another.js
- 07Quality Assurance/01Quality Assurance and Testing with Chai/10Test if a Value Falls within a Specific Range.js
- 07Quality Assurance/01Quality Assurance and Testing with Chai/11Test if a Value is an Array.js
completed more challenges from mongoldb and mongoose and also from js testing with mocha and chai
> add: challenges from mongodb and mongoose and testing

- 07Quality Assurance/01Quality Assurance and Testing with Chai/11Test if a Value is an Array.js
- 07Quality Assurance/01Quality Assurance and Testing with Chai/12Test if an Array Contains an Item.js
- 07Quality Assurance/01Quality Assurance and Testing with Chai/13Test if a Value is a String.js
- 07Quality Assurance/01Quality Assurance and Testing with Chai/14Test if a String Contains a Substring.js
- 07Quality Assurance/01Quality Assurance and Testing with Chai/15Use Regular Expressions to Test a String.js
- 07Quality Assurance/01Quality Assurance and Testing with Chai/16Test if an Object has a Property.js
- 07Quality Assurance/01Quality Assurance and Testing with Chai/17Test if a Value is of a Specific Data Structure Type.js
- 07Quality Assurance/01Quality Assurance and Testing with Chai/18Test if an Object is an Instance of a Constructor.js
- 07Quality Assurance/01Quality Assurance and Testing with Chai/19Run Functional Tests on API Endpoints using Chai-HTTP.js
- 07Quality Assurance/01Quality Assurance and Testing with Chai/20Run Functional Tests on API Endpoints using Chai-HTTP II.js
completed challenges of node from backend development and API's
> add: more files from freeCodeCamp Challenges

- 07Quality Assurance/01Quality Assurance and Testing with Chai/20Run Functional Tests on API Endpoints using Chai-HTTP II.js
- 07Quality Assurance/01Quality Assurance and Testing with Chai/21Run Functional Tests on an API Response using Chai-HTTP III - PUT method.js
- 07Quality Assurance/01Quality Assurance and Testing with Chai/22Run Functional Tests on an API Response using Chai-HTTP IV - PUT method.js
completed challenges from quality assurance certification.
> add: Quality assurance module challenges completed in freecodecamp

- 08Scientific Computing with Python/01Python for Everybody/All solutions.txt
- 08Scientific Computing with Python/01Python for Everybody/testing.py
completed the module of scientific computing with python in freecodecamp
> add: challenges from python scientific computing of freecodecamp

- 09Data Analysis with Python Certification/Data Analysis with Python/All solutions.txt
- 09Data Analysis with Python Certification/Numpy/All solutions.tx
completed more challenges from freeCodeCamps Data Analysis with Python Certification
> add: completed challenges Data Analysis with Python Certification

- 03Frontend Development Libraries/07Module final projects code/Build a Markdown Previewer/index.html
- 03Frontend Development Libraries/07Module final projects code/Build a Markdown Previewer/index.js
- 03Frontend Development Libraries/07Module final projects code/Build a Markdown Previewer/styles.css
completed projects for module completion in freeCodeCamp Frontend Development and Libraries
> add: completed frontend modules projects in freeCodeCamp

- 03Frontend Development Libraries/07Module final projects code/Build a Drum Machine/index.html
this will probably be the final commit for this account
> submitting maybe final commit

- 01(New) Responsive Web Design/02Learn CSS by Building a Cafe Menu/step003.html
- 01(New) Responsive Web Design/02Learn CSS by Building a Cafe Menu/step004.html
- 01(New) Responsive Web Design/02Learn CSS by Building a Cafe Menu/step008.html
made changes to the solutions to pass the recent changes to fCC challenges.
> modify: updated solutions to Learn CSS by building a Cafe Menu

- 10Machine Learning with Python certification/01Tensorflow/All Solutions.txt
added solutions to a new module of fCC Machine learning with Python
> add: solutions to 01Tensorflow module of fCC

- 10Machine Learning with Python certification/02How Neural Networks work/All Solutions.txt
completed the module Machine Learning with Python
> add: solutions for Machine learning with Python

- 02JavaScript Algorithms and Data Structures (Beta)/Learn Introductory JavaScript by Building a Pyramid Generator/step001.js
- 02JavaScript Algorithms and Data Structures (Beta)/Learn Introductory JavaScript by Building a Pyramid Generator/step002.js
- 02JavaScript Algorithms and Data Structures (Beta)/Learn Introductory JavaScript by Building a Pyramid Generator/step003.js
- 02JavaScript Algorithms and Data Structures (Beta)/Learn Introductory JavaScript by Building a Pyramid Generator/step004.js
- 02JavaScript Algorithms and Data Structures (Beta)/Learn Introductory JavaScript by Building a Pyramid Generator/step005.js
- 02JavaScript Algorithms and Data Structures (Beta)/Learn Introductory JavaScript by Building a Pyramid Generator/step006.js
- 02JavaScript Algorithms and Data Structures (Beta)/Learn Introductory JavaScript by Building a Pyramid Generator/step007.js
- 02JavaScript Algorithms and Data Structures (Beta)/Learn Introductory JavaScript by Building a Pyramid Generator/step008.js
- 02JavaScript Algorithms and Data Structures (Beta)/Learn Introductory JavaScript by Building a Pyramid Generator/step009.js
- 02JavaScript Algorithms and Data Structures (Beta)/Learn Introductory JavaScript by Building a Pyramid Generator/step010.js
- 02JavaScript Algorithms and Data Structures (Beta)/Learn Introductory JavaScript by Building a Pyramid Generator/step011.js
- 02JavaScript Algorithms and Data Structures (Beta)/Learn Introductory JavaScript by Building a Pyramid Generator/step012.js
- 02JavaScript Algorithms and Data Structures (Beta)/Learn Introductory JavaScript by Building a Pyramid Generator/step013.js
- 02JavaScript Algorithms and Data Structures (Beta)/Learn Introductory JavaScript by Building a Pyramid Generator/step014.js
- 02JavaScript Algorithms and Data Structures (Beta)/Learn Introductory JavaScript by Building a Pyramid Generator/step015.js
- 02JavaScript Algorithms and Data Structures (Beta)/Learn Introductory JavaScript by Building a Pyramid Generator/step016.js
- 02JavaScript Algorithms and Data Structures (Beta)/Learn Introductory JavaScript by Building a Pyramid Generator/step017.js
- 02JavaScript Algorithms and Data Structures (Beta)/Learn Introductory JavaScript by Building a Pyramid Generator/step018.js
- 02JavaScript Algorithms and Data Structures (Beta)/Learn Introductory JavaScript by Building a Pyramid Generator/step019.js
completed new challenges in JS new module fCC
> ADD: files for new challenges

- 02JavaScript Algorithms and Data Structures (Beta)/Learn Introductory JavaScript by Building a Pyramid Generator/step032.js
- 02JavaScript Algorithms and Data Structures (Beta)/Learn Introductory JavaScript by Building a Pyramid Generator/step033.js
implemented and solved more challenges of JS module track in fCC
> ADD: challenges completed in JS fCC module

- 02JavaScript Algorithms and Data Structures (Beta)/01Learn Introductory JavaScript by Building a Pyramid Generator/step036.js
- 02JavaScript Algorithms and Data Structures (Beta)/01Learn Introductory JavaScript by Building a Pyramid Generator/step037.js
- 02JavaScript Algorithms and Data Structures (Beta)/01Learn Introductory JavaScript by Building a Pyramid Generator/step038.js
- 02JavaScript Algorithms and Data Structures (Beta)/01Learn Introductory JavaScript by Building a Pyramid Generator/step039.js
- 02JavaScript Algorithms and Data Structures (Beta)/01Learn Introductory JavaScript by Building a Pyramid Generator/step040.js
- 02JavaScript Algorithms and Data Structures (Beta)/01Learn Introductory JavaScript by Building a Pyramid Generator/step041.js
- 02JavaScript Algorithms and Data Structures (Beta)/01Learn Introductory JavaScript by Building a Pyramid Generator/step042.js
- 02JavaScript Algorithms and Data Structures (Beta)/01Learn Introductory JavaScript by Building a Pyramid Generator/step043.js
- 02JavaScript Algorithms and Data Structures (Beta)/01Learn Introductory JavaScript by Building a Pyramid Generator/step044.js
- 02JavaScript Algorithms and Data Structures (Beta)/01Learn Introductory JavaScript by Building a Pyramid Generator/step045.js
- 02JavaScript Algorithms and Data Structures (Beta)/01Learn Introductory JavaScript by Building a Pyramid Generator/step046.js
- 02JavaScript Algorithms and Data Structures (Beta)/01Learn Introductory JavaScript by Building a Pyramid Generator/step047.js
- 02JavaScript Algorithms and Data Structures (Beta)/01Learn Introductory JavaScript by Building a Pyramid Generator/step048.js
- 02JavaScript Algorithms and Data Structures (Beta)/01Learn Introductory JavaScript by Building a Pyramid Generator/step049.js
- 02JavaScript Algorithms and Data Structures (Beta)/01Learn Introductory JavaScript by Building a Pyramid Generator/step050.js
- 02JavaScript Algorithms and Data Structures (Beta)/01Learn Introductory JavaScript by Building a Pyramid Generator/step051.js
- 02JavaScript Algorithms and Data Structures (Beta)/01Learn Introductory JavaScript by Building a Pyramid Generator/step052.js
- 02JavaScript Algorithms and Data Structures (Beta)/01Learn Introductory JavaScript by Building a Pyramid Generator/step053.js
- 02JavaScript Algorithms and Data Structures (Beta)/01Learn Introductory JavaScript by Building a Pyramid Generator/step054.js
- 02JavaScript Algorithms and Data Structures (Beta)/01Learn Introductory JavaScript by Building a Pyramid Generator/step055.js
- 02JavaScript Algorithms and Data Structures (Beta)/01Learn Introductory JavaScript by Building a Pyramid Generator/step056.js
- 02JavaScript Algorithms and Data Structures (Beta)/01Learn Introductory JavaScript by Building a Pyramid Generator/step057.js
- 02JavaScript Algorithms and Data Structures (Beta)/01Learn Introductory JavaScript by Building a Pyramid Generator/step058.js
- 02JavaScript Algorithms and Data Structures (Beta)/01Learn Introductory JavaScript by Building a Pyramid Generator/step059.js
- 02JavaScript Algorithms and Data Structures (Beta)/01Learn Introductory JavaScript by Building a Pyramid Generator/step060.js
completed some new challenges in the JS DS&A course from fCC
> ADD: completed JS challenges

- 02JavaScript Algorithms and Data Structures (Beta)/01Learn Introductory JavaScript by Building a Pyramid Generator/step012.js
- 02JavaScript Algorithms and Data Structures (Beta)/01Learn Introductory JavaScript by Building a Pyramid Generator/step013.js
modified code for two of the files will review later.
> made changes to two files as per new changes
